[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bevy_ecs = "0.12.1"

[dependencies.godot]
git = "https://github.com/godot-rust/gdext"
rev = "c92de581da1cab8b49d8e7e822abd2055385ae24"
features = ["experimental-threads"]
